name: CustomAirdropPlugin
version: '${version}'

main: Bzbxddbx.customAirdropPlugin.CustomAirdropPlugin
api-version: '26.2'
load: POSTWORLD

commands:
  airdropstart:
    description: Start a custom airdrop event
    usage: /airdropstart
  airdrop:
    description: Manage the airdrop plugin
    usage: /airdrop <reload>