name: CustomAirdropPlugin
version: '${version}'

main: Bzbxddbx.customAirdropPlugin.CustomAirdropPlugin
api-version: '26.2'
load: POSTWORLD

permissions:
  airdrop.command.start:
    description: Allows starting a custom airdrop event
    default: op
  airdrop.command.reload:
    description: Allows reloading the loot configuration on the fly
    default: op
  airdrop.command.stop:
    description: Allows stopping the active airdrop event
    default: op